FROM node:12.6.0
ADD . /server-tests
WORKDIR /server-tests
COPY . /server-tests
RUN npm install
RUN npm install -g mocha nyc

## LIFE SAVER SCRIPT - waits for mongoose to be fully up & running
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

# Use this line instead if you don't want to run coverage
# CMD /wait && npm test
CMD /wait && npm run test-with-coverage
